ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
default_platform(:ios)

# 打包
platform :ios do

  # 打包
  lane :ipaPackage do |options|
    package(
      configuration: options[:configuration],
      export_method: options[:export_method],
      build: options[:build],
      scheme: options[:scheme],
      is_analyze_swiftlint: options[:is_analyze_swiftlint],
      is_detect_duplicity_code: options[:is_detect_duplicity_code],
      is_detect_unused_code: options[:is_detect_unused_code],
      is_detect_unused_image: options[:is_detect_unused_image],
      changelog: options[:changelog], # fir 更新日志
      release_notes: options[:release_notes] # 配合 jenkins 传参上传 appstore 格式为 { \"zh-Hans\": \"修复问题\", \"en-US\": \"bugfix\"} JSON 字符串
    )
  end

  # 代码分析
  lane :analyzeSwiftlint do |options|
    analyze_swiftlint(
      is_all: options[:is_all],
      configuration: options[:configuration],
      commit_hash: options[:commit_hash]
    )
  end

  # 重复代码检查
  lane :detectDuplicityCode do |options|
    detect_duplicity_code(
      is_all: options[:is_all],
      commit_hash: options[:commit_hash]
    )
  end

  # 无用代码检查
  lane :detectUnusedCode do |options|
    detect_unused_code(
      configuration: options[:configuration]
    )
  end

  # 无用图片检查
  lane :detectUnusedImage do
    detect_unused_image()
  end

end
